config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks, :projects, :contexts, :pomodoros
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tasks
end

app/models/pomodoro.rb
class Pomodoro < ApplicationRecord
  belongs_to :user
  has_many :pomodoro_logs
end

app/models/pomodoro_log.rb
class PomodoroLog < ApplicationRecord
  belongs_to :pomodoro
  belongs_to :task
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :pomodoro_logs
  has_many :pomodoros, through: :pomodoro_log
  has_and_belongs_to_many :contexts
  has_and_belongs_to_many :projects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #Associations
  has_many :tasks
  has_many :pomodoros
  has_many :projects
  has_many :contexts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
  end
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :authenticate_user!
  def index
    @contexts = current_user.contexts
  end

  def new
    @context = Context.new
  end

  def create
    @context = Context.new(context_params)
    @context.user = current_user;
    if @context.save
      redirect_to contexts_path
    else
      render 'new'
    end
  end

  def edit
    @context = Context.find(params[:id])
  end

  def destroy
    @context = Context.find(params[:id])
    @context.destroy
    redirect_to contexts_path
  end

  def update
    @context = Context.find(params[:id])
    if @context.update(context_params)
      redirect_to contexts_path
    end
  end

  private

  def context_params
    params.require(:context).permit(:name)
  end
end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user;
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
    @projects = current_user.projects
    @contexts = current_user.contexts
  end

  def create
    @task = Task.new
    @params = params[:task]
    @task.user = current_user
    @task.name = @params[:name]
    @task.priority = @params[:priority]
    @task.contexts << Context.find(@params[:contexts]) rescue nil
    @task.projects << Project.find(@params[:projects]) rescue nil
    if !(Context.exists?(@params[:contexts]))
        redirect_to new_task_path, :notice => "Can't save the task: fill all the required fields"
    elsif @task.save
      redirect_to tasks_path
    else
      redirect_to new_task_path
    end
  end

  def edit
    @task = Task.find(params[:id])
    @projects = current_user.projects
    @contexts = current_user.contexts
  end

  def update
    @task = Task.find(params[:id])
    @params = params[:task]
    @task.user = current_user
    @task.name = @params[:name]
    @task.priority = @params[:priority]
    @task.contexts << Context.find(@params[:contexts])
    @task.projects << Project.find(@params[:projects])
    if @task.save
      redirect_to tasks_path
    else
      redirect_to new_task_path
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:name,:due,:priority,:contexts,:projects)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/pomodoros_helper.rb
module PomodorosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/contexts/edit.html.erb
<%= form_for @context, url: context_path(@context),
  html: {class: "ui form"}, 
  method: :patch do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit "Save", :class=> 'ui green button' %>
<% end %>

app/views/contexts/index.html.erb
<h1>Contexts</h1>
 
<ul class="ui list">
  <% @contexts.each do |context| %>
    <li class="item"> 
      <span class="right floated content">
        <a href=<%="#{contexts_path}/#{context.id}"%>
          data-method="delete">
          <i class="erase red icon"></i>
        </a>
        <a href=<%=edit_context_path(context.id)%>>
          <i class="edit green icon"></i>
        </a>
      </span>
      <i class="At teal icon"></i> 
      <span class="content">
        <%= context.name %>
      </span>
    </li>
  <% end %>
</ul>

app/views/contexts/new.html.erb
<%= form_for @context, url: {action: "create"},
  html: {class: "ui form"} do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit "New", :class=> 'ui green button' %>
<% end %>

app/views/contexts/show.html.erb
<h1>Contexts#show</h1>
<p>Find me in app/views/contexts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoRails</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <div class="ui grid">
        <div class="four wide column">
          <%= render "shared/nav_menu"%>
        </div>
        <div class="twelve wide stretched column">
          <div class="ui container">
          <% flash.each do |key, value| %>
            <h2><%= value %></h2>
          <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %><!--Devise views-->
      <%=yield %>
    <% end %>
  </body>
</html

app/views/pomodoros/edit.html.erb
<h1>Pomodoros#edit</h1>
<p>Find me in app/views/pomodoros/edit.html.erb</p>

app/views/pomodoros/index.html.erb
<h1>Pomodoros#index</h1>
<p>Find me in app/views/pomodoros/index.html.erb</p>

app/views/pomodoros/new.html.erb
<h1>Pomodoros#new</h1>
<p>Find me in app/views/pomodoros/new.html.erb</p>

app/views/pomodoros/show.html.erb
<h1>Pomodoros#show</h1>
<p>Find me in app/views/pomodoros/show.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/shared/_nav_menu.html.erb
<nav>
  <ul class="ui vertical tabular fluid menu">
    <li class="<%=request.original_fullpath == '/tasks' ? 'active item': 'item'%>">
      <a href="/tasks/new"><i class="green add square icon"></i></a>
      <a href="/tasks">Tasks</a>
      <div class="ui left pointing label"><%= current_user.tasks.size %></div> 
    </li>
    <li class="<%=request.original_fullpath == '/projects' ? 'active item': 'item'%>">
      <a href="/projects/new"><i class="green add square icon"></i></a>
      <a href="/projects">Projects</a>
      <div class="ui left pointing label"><%= current_user.projects.size %></div> 
    </li>
    <li class="<%=request.original_fullpath == '/contexts' ? 'active item': 'item'%>">
      <a href="/contexts/new"><i class="green add square icon"></i></a>
      <a href="/contexts">Contexts</a>
      <div class="ui left pointing label"><%= current_user.contexts.size %></div> 
    </li>
    <li class="<%=request.original_fullpath == '/pomodoros' ? 'active item': 'item'%>">
      <a href="/pomodoros/new"><i class="green add square icon"></i></a>
      <a href="/pomodoros">Pomodoros</a>
      <div class="ui left pointing label"><%= current_user.pomodoros.size %></div> 
    </li>
    <li class="item">
      <%= link_to("Log Out", destroy_user_session_path, 
        :method => :delete) %>
    </li>
  </ul>
</nav>

app/views/tasks/edit.html.erb
<%= form_for @task, url: task_path(@task),
  html: {class: "ui form"}, 
  method: :patch do |t| %>
  <div class="field">
    <%= t.label :name %>
    <%= t.text_field :name %>
    <%= t.label :priority %>
    <%= t.select(:priority) do %>
      <% [["A", 1], ["B", 2], ["C", 3], ["D", 4]].each do |p| -%>
        <%= content_tag(:option, p.first, value: p.last) %>
      <% end %>
    <% end %>
    <%= t.label :context %>
    <%= t.collection_select(:contexts, @contexts, :id, :name) %>
    <%= t.label :project %>
    <%= t.collection_select(:projects, @projects, :id, :name) %>
    <%= t.label :due %>
    <%= t.date_field :due %>
  </div>
  <%= t.submit "Save", :class=> 'ui green button' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
 
<ul class="ui list">
  <% @tasks.each do |task| %>
    <li class='item'> 
      <span class="right floated content">
        <a href=<%="#{tasks_path}/#{task.id}"%>
          data-method="delete">
          <i class="erase red icon"></i>
        </a>
        <a href=<%=edit_task_path(task.id)%>>
          <i class="edit green icon"></i>
        </a>
      </span>
      <i class='tasks <%=
        if task.priority == 1
          "red"
        elsif task.priority == 2
          "orange"
        elsif task.priority == 3
          "green"
        end
        %> icon'></i> 
      <span class="content">
        <%= task.name %>
        <%= task.due %>
        <% task.projects.each do |project| %>
          <i class="plus teal icon"></i><%= project.name %>
        <% end %>
        <% task.contexts.each do |context| %>
          <i class="at teal icon"></i><%= context.name %>
        <% end %>
      </span>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_for @task, url: {action: "create"},
  html: {class: "ui form"} do |t| %>
  <div class="field">
    <%= t.label :name %>
    <%= t.text_field :name %>
    <%= t.label :priority %>
    <%= t.select(:priority) do %>
      <% [["A", 1], ["B", 2], ["C", 3], ["D", 4]].each do |p| -%>
        <%= content_tag(:option, p.first, value: p.last) %>
      <% end %>
    <% end %>
    <%= t.label :context %>
    <%= t.collection_select(:contexts, @contexts, :id, :name) %>
    <%= t.label :project %>
    <%= t.collection_select(:projects, @projects, :id, :name) %>
    <%= t.label :due %>
    <%= t.date_select :due %>
  </div>
    <%= t.submit "Create", :class=> 'ui green button' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>